server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: member-service
        uri: lb://member-service
        predicates:
        - Path=/api/v1/member/**
      - id: claim-service
        uri: lb://claim-service
        predicates:
        - Path=/api/v1/claim/**